warning: in the working copy of 'server/polityLabels.test.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/AI/gameplay.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/AI/gameplaySchemas.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/AI/nativeUnitDirector.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/AI/nativeWorldDirector.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/AI/nativeWorldIntegrity.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/GameUI/actions.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/GameUI/advisor.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/GameUI/chat.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/GameUI/main.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/GameUI/time.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/Map/Cities.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/Map/Nations.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/Map/World.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/Map/unitsController.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/Map/useWorldState.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/Game/Map/vnext/polityBoundariesWorker.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/runtime/assets.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/runtime/countryLabels.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/runtime/gameState.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/runtime/preload.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/styles.css', LF will be replaced by CRLF the next time Git touches it
