import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const main = fs.readFileSync(new URL("./main.jsx", import.meta.url), "utf8");
const gameplay = fs.readFileSync(new URL("./gameplay.js", import.meta.url), "utf8");
const settings = fs.readFileSync(new URL("../GameUI/settings.jsx", import.meta.url), "utf8");
const time = fs.readFileSync(new URL("../GameUI/time.jsx", import.meta.url), "utf8");

test("callAI composes the global emergency-stop signal before provider routing and always releases it", () => {
  assert.match(main, /import \{ beginAiRequestScope \} from "\.\/aiRequestControl\.js";/);
  assert.match(main, /const requestScope = beginAiRequestScope\(providerOpts\.signal\);/);
  assert.match(main, /providerOpts\.signal = requestScope\.signal;/);
  assert.match(main, /finally \{\s*requestScope\.finish\(\);\s*\}/);
});

// "Cancel all AI requests" during a time skip. The stop reached the request and
// not the skip: a single-request skip took it for a failed call and wrote its
// canned turn ("Turn generated by fallback: Cancelled by player."), and a longer
// one went on to its next request. It ends as the skip's own Cancel does.
test("the emergency stop ends a time skip as its own Cancel does: no canned turn, a cancelled turn in the log", () => {
  const from = gameplay.indexOf("const runJsonTask = async");
  const runner = gameplay.slice(from, gameplay.indexOf("// When a pass is due", from));
  assert.match(runner, /if \(isCancelAllAbort\(actualError\)\) cancelledAll = actualError;/);
  const handedUp = runner.indexOf('if (cancelledAll && ["jumpForward", "autoJumpForward"].includes(taskKey)) {');
  const salvage = runner.indexOf("if (salvageCandidate) {");
  const canned = runner.indexOf("payload: await fallback(),");
  assert.ok(handedUp > -1, "handed up as the abort it is");
  assert.match(runner.slice(handedUp, handedUp + 140), /throw cancelledAll;/);
  assert.ok(salvage > handedUp, "before an earlier answer is salvaged into a turn");
  assert.ok(canned > handedUp, "and before the canned fallback");

  // What it is handed up to treats an AbortError as the player's cancel.
  assert.match(gameplay, /\/\/ A deliberate cancel must still cancel\.\s*if \(signal\?\.aborted \|\| error\?\.name === "AbortError"\) throw error;/);
  assert.match(time, /if \(controller\.signal\.aborted \|\| jumpError\?\.name === "AbortError"\) \{/);
});

test("the Timeline cancels its skip, or its held turn's retry, on every press of the emergency stop", () => {
  assert.match(time, /import \{ AI_REQUEST_CONTROL_EVENT \} from "\.\.\/AI\/aiRequestControl\.js";/);
  assert.match(time, /if \(event\?\.detail && "cancelled" in event\.detail\) cancelJump\(\);/);
  assert.match(time, /window\.addEventListener\(AI_REQUEST_CONTROL_EVENT, stopWithTheRest\);/);
  assert.match(time, /window\.removeEventListener\(AI_REQUEST_CONTROL_EVENT, stopWithTheRest\);/);
  // The same abort the Cancel button raises, on the controller a retry holds too.
  assert.match(time, /const cancelJump = useCallback\(\(\) => \{[\s\S]{0,400}?jumpAbortRef\.current\?\.abort\(new DOMException\("Timeline jump cancelled\.", "AbortError"\)\);/);
});

test("Settings exposes one emergency stop in the canonical AI requests section", () => {
  assert.match(settings, /Cancel all AI requests/);
  assert.match(settings, /cancelAllAiRequests\(\)/);
  assert.match(settings, /AI_REQUEST_CONTROL_EVENT/);
  assert.match(settings, /Cancels all live AI generation requests the client can abort/);
});
