/*! Open Historia — the built-in flags that ship with the game © 2026 Nicholas Krol, AGPL-3.0-or-later (see LICENSE). */
// Downloads the game's built-in flags into public/flags/, so they are part of every
// build (the website, the desktop app, the Android app) and draw with no network:
//
//   public/flags/<code>.svg        what the panels, pickers and chat draw
//   public/flags/w160/<code>.png   what the map's unit counters rasterise (a
//                                  canvas cannot size an SVG that has no width,
//                                  and some of these have none)
//
// and writes src/runtime/generated/bundledFlagCodes.js, the list the game maps a
// flagcdn.com address onto (countryFlags.js bundledFlagUrl). Scenarios and saves
// keep storing the flagcdn address; only where a flag is drawn does it become the
// bundled copy.
//
// The set is every code flagcdn.com serves (Flagpedia.net's flags, public domain)
// except the US states: 7.9 MB of seals the game never asks for. That leaves the
// countries and territories, the EU, the UN, Kosovo and the four UK nations.
//
//   node scripts/fetch-flags.mjs
//
// Run it again only to pick up a flag that changed upstream; the files are
// committed, so a build never needs the network for them.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "public", "flags");
const CODES_MODULE = path.join(ROOT, "src", "runtime", "generated", "bundledFlagCodes.js");
const CDN = "https://flagcdn.com";

export const isBundledCode = (code) => /^[a-z]{2}(?:-[a-z]{2,3})?$/.test(code) && !code.startsWith("us-");

const fetchOk = async (url) => {
  for (let attempt = 1; ; attempt += 1) {
    try {
      const response = await fetch(url);
      if (!response.ok) throw new Error(`${url} answered ${response.status}`);
      return Buffer.from(await response.arrayBuffer());
    } catch (error) {
      if (attempt >= 3) throw error;
      await new Promise((resolve) => setTimeout(resolve, 500 * attempt));
    }
  }
};

const main = async () => {
  const names = JSON.parse((await fetchOk(`${CDN}/en/codes.json`)).toString("utf8"));
  const codes = Object.keys(names).map((code) => code.toLowerCase()).filter(isBundledCode).sort();
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(path.join(OUT, "w160"), { recursive: true });

  let bytes = 0;
  const queue = [...codes];
  const worker = async () => {
    for (let code = queue.shift(); code; code = queue.shift()) {
      const svg = await fetchOk(`${CDN}/${code}.svg`);
      const png = await fetchOk(`${CDN}/w160/${code}.png`);
      fs.writeFileSync(path.join(OUT, `${code}.svg`), svg);
      fs.writeFileSync(path.join(OUT, "w160", `${code}.png`), png);
      bytes += svg.length + png.length;
    }
  };
  await Promise.all(Array.from({ length: 8 }, worker));

  fs.writeFileSync(
    path.join(OUT, "README.md"),
    [
      "# Built-in flags",
      "",
      "The flags the game draws for standard countries, shipped with every build so they",
      "show offline and no flag request leaves the device. From Flagpedia.net's",
      "flagcdn.com set, which is in the public domain. `<code>.svg` for the interface,",
      "`w160/<code>.png` for the map's unit counters.",
      "",
      "Generated by `node scripts/fetch-flags.mjs`; do not edit by hand.",
      "",
    ].join("\n"),
  );
  fs.writeFileSync(
    CODES_MODULE,
    [
      "/* AUTO-GENERATED by scripts/fetch-flags.mjs — do not edit. */",
      "// The flag codes shipped in public/flags/ (<code>.svg and w160/<code>.png).",
      `export default ${JSON.stringify(codes)};`,
      "",
    ].join("\n"),
  );
  console.log(`${codes.length} flags, ${(bytes / 1e6).toFixed(1)} MB, in ${path.relative(ROOT, OUT)}/`);
};

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error.message || error);
    process.exit(1);
  });
}
